/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package di.uniba.it.tee2.gui;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author pierpaolo
 */
public class DocDialog extends javax.swing.JDialog {

    /**
     * Creates new form DocDialog
     */
    public DocDialog(java.awt.Frame parent, boolean modal, String docId, String snip) {
        super(parent, modal);
        initComponents();
        this.setTitle("DOC VIEW - "+docId);
        initMy(docId, snip);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(640, 480));
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    private void initMy(String docId, String snip) {
        try {
            String text = TEEgui.search.getDocumentText(docId);
            int indexOf = text.indexOf(snip);
            jTextPane1.setText(text);

            if (indexOf > -1) {
                StyledDocument sdoc = jTextPane1.getStyledDocument();
                SimpleAttributeSet aset = new SimpleAttributeSet();
                StyleConstants.setBackground(aset, Color.yellow);
                sdoc.setCharacterAttributes(indexOf, snip.length(), aset, false);
            }
        } catch (IOException ex) {
            Logger.getLogger(DocDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
